Fix Watcher test 'testVars' (#82135)
The error that caused his test be muted is
java.lang.AssertionError: Count is 2 hits but 1 was expected.
from: assertHitCount(searchResponse, 1L);
when searching for watch records.

It is believed this is due to the cron scheduler executing a
second watch. The change here is to use a long interval
schedule instead of the cron scheduler.

Fixes #67908